### ISSUE TITLE
Impossible import

### ISSUE THREAD

**Issue by basz** [bgmeulem/Luminet#2]
from black_hole import *

Nothing leaves a black hole. This is not possible...

**Comment by bgmeulem** [comment]
Thank you for bringing this oversight to my attention.

Luckily, we are visualizing the accretion disk, rather than the black hole itself. While this mass is not lost forever, it is being consumed ever so slowly by the black hole by accretion effects. Assuming low angular momentum (as is our case with a Swarzschild black hole), and depending on various properties, the accretion rate may vary between $10^{-8} - 10^{-2}$ (Bu and Yang, 2019). To account for accretion effects, you could always do something like:
```python
acc_rate = 1e-6  # in units of Eddington luminosity per c^2
import numpy as np
if np.random.random() > accretion_rate:
    import black_hole as bh
else:
    raise UserWarning("Your import fell into the black hole :(")
```

[1] Bu, D.-F. and Yang, X.-H., “What is the real accretion rate on to a black hole for low-angular-momentum accretion?”, <i>Monthly Notices of the Royal Astronomical Society</i>, vol. 484, no. 2, pp. 1724–1734, 2019. doi:10.1093/mnras/stz050.
